# Generated by Django 6.0.5 on 2026-08-05 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('feedback', '0016_alter_feedback_category_alter_feedback_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stability_change_threshold', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('significant_change_threshold', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('sudden_spike_percentage', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('sudden_spike_minimum_count', models.PositiveIntegerField(default=5)),
                ('minimum_sample_insufficient', models.PositiveIntegerField(default=4)),
                ('minimum_sample_low_volume', models.PositiveIntegerField(default=19)),
                ('low_rating_threshold', models.DecimalField(decimal_places=2, default=2.5, max_digits=3)),
                ('minimum_recurring_periods', models.PositiveIntegerField(default=2)),
                ('minimum_cross_facility_count', models.PositiveIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Period'), ('facility', 'Facility')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('submission_source', models.CharField(blank=True, max_length=32)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('comparison_start', models.DateField(blank=True, null=True)),
                ('comparison_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executive_summary', models.TextField(blank=True)),
                ('management_comments', models.TextField(blank=True)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_intelligence_reports', to=settings.AUTH_USER_MODEL)),
                ('collection_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_reports', to='feedback.collectionsession')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_reports', to='facilities.facility')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_intelligence_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_intelligence_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
                'permissions': [('review_intelligencereport', 'Can review intelligence report'), ('approve_intelligencereport', 'Can approve intelligence report'), ('regenerate_intelligencereport', 'Can regenerate intelligence report')],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceReportCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('period_key', models.CharField(max_length=32)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('scope', 'period_key')},
            },
        ),
        migrations.CreateModel(
            name='IntelligenceReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('executive_summary', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('supporting_statistics', models.JSONField(blank=True, default=dict)),
                ('insight_snapshot', models.JSONField(blank=True, default=list)),
                ('topic_snapshot', models.JSONField(blank=True, default=list)),
                ('generation_settings', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_intelligence_report_versions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='intelligence.intelligencereport')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('metric', 'Metric'), ('trend', 'Trend'), ('emerging_issue', 'Emerging issue'), ('recurring_issue', 'Recurring issue'), ('positive_development', 'Positive development'), ('facility_alert', 'Facility alert'), ('topic', 'Topic')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], default='informational', max_length=16)),
                ('direction', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable'), ('sudden_spike', 'Sudden spike'), ('insufficient_data', 'Insufficient data')], default='stable', max_length=24)),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('insufficient', 'Insufficient')], default='insufficient', max_length=16)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('metric_name', models.CharField(blank=True, max_length=255)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comparison_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('absolute_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_insights', to='facilities.facility')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='intelligence.intelligencereport')),
                ('report_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='intelligence.intelligencereportversion')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='intelligencereportversion',
            constraint=models.UniqueConstraint(fields=('report', 'version'), name='unique_intelligence_report_version'),
        ),
    ]
