# Generated by Django 4.2.11 on 2026-04-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('Waiting Time', 'Waiting Time'), ('Staff Attitude', 'Staff Attitude'), ('Privacy', 'Privacy'), ('Service Quality', 'Service Quality'), ('Availability of Medication', 'Availability of Medication'), ('Cleanliness', 'Cleanliness'), ('Youth Friendly Services', 'Youth Friendly Services')], max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('age_group', models.CharField(blank=True, choices=[('Under 18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55+', '55+')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='facilities.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
