# Generated by Django 4.2.11 on 2026-06-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='aob',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='cash_payment',
            field=models.CharField(blank=True, choices=[('Less than K20', 'Less than K20'), ('Between K20 and K50', 'Between K20 and K50'), ('Between K50 and K100', 'Between K50 and K100'), ('More than K100', 'More than K100'), ("I don't remember", "I don't remember"), ('other', 'other')], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='chance',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='change',
            field=models.CharField(blank=True, choices=[('More health workers available', 'More health workers available'), ('More medicines in stock', 'More medicines in stock'), ('Shorter waiting time', 'Shorter waiting time'), ('Lower cost of services', 'Lower cost of services'), ('Better staff attitude', 'Better staff attitude'), ('Longer opening hours', 'Longer opening hours'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='cost',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA'), ('Not sure', 'Not sure')], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Seeing', 'Seeing'), ('Hearing', 'Hearing'), ('Mobility', 'Mobility'), ('Remembering', 'Remembering'), ('Self-care', 'Self-care'), ('Communicating', 'Communicating'), ('None', 'None')], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='distance',
            field=models.CharField(blank=True, choices=[('Less than 5 km', 'Less than 5 km'), ('Between 5 km and 10 km', 'Between 5 km and 10 km'), ('More than 10 km', 'More than 10 km')], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='insurance',
            field=models.CharField(blank=True, choices=[('NHIMA (National Health Insurance)', 'NHIMA (National Health Insurance)'), ('Private Insurance', 'Private Insurance'), ('Both', 'Both'), ('None', 'None'), ('Not sure', 'Not sure')], max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='medicines',
            field=models.CharField(blank=True, choices=[('Yes, got all medicines here', 'Yes, got all medicines here'), ('No, told to buy some at a pharmacy', 'No, told to buy some at a pharmacy'), ('No, did not get the medicines at all', 'No, did not get the medicines at all'), ('No medicines were prescribed', 'No medicines were prescribed')], max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='no_insurance_reason',
            field=models.CharField(blank=True, choices=[('I do not have any health insurance', 'I do not have any health insurance'), ('I have NHIMA, but I forgot my card / number', 'I have NHIMA, but I forgot my card / number'), ('I have private insurance, but I forgot my card / number', 'I have private insurance, but I forgot my card / number'), ('I have NHIMA, but the facility did not accept it', 'I have NHIMA, but the facility did not accept it'), ('I have private insurance, but this health post does not accept it ', 'I have private insurance, but this health post does not accept it '), ('My insurance does not cover the services I needed today', 'My insurance does not cover the services I needed today'), ('I chose to pay out-of-pocket instead', 'I chose to pay out-of-pocket instead'), ('Not sure', 'Not sure'), ('Other', 'Other')], max_length=128),
        ),
        migrations.AddField(
            model_name='feedback',
            name='payment',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reason_not_chance',
            field=models.CharField(blank=True, choices=[('Very poor people', 'Very poor people'), ('People who live far away', 'People who live far away'), ('Women', 'Women'), ('Elderly people', 'Elderly people'), ('People with disabilities', 'People with disabilities'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reason_not_received',
            field=models.CharField(blank=True, choices=[('Health worker was not available', 'Health worker was not available'), ('Medicines were out of stock', 'Medicines were out of stock'), ('Laboratory test or equipment not available', 'Laboratory test or equipment not available'), ('I was asked to return another day', 'I was asked to return another day'), ('I was referred to another facility', 'I was referred to another facility'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='received_service',
            field=models.CharField(blank=True, choices=[('Yes, I received everything I needed', 'Yes, I received everything I needed'), ('No, I did not receive what I needed', 'No, I did not receive what I needed'), ('Partially, I received some but not all', 'Partially, I received some but not all')], max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='referral',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='revisit',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not sure', 'Not sure')], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='service',
            field=models.CharField(blank=True, choices=[('Treatment for illness/injury', 'Treatment for illness/injury'), ('Child health: immunization or sick child', 'Child health: immunization or sick child'), ('Maternal health: antenatal, postnatal, family planning', 'Maternal health: antenatal, postnatal, family planning'), ('Chronic disease care: hypertension, diabetes, HIV, TB', 'Chronic disease care: hypertension, diabetes, HIV, TB'), ('Laboratory test or scan only', 'Laboratory test or scan only'), ('To collect medicines only', 'To collect medicines only'), ('Multiple reasons', 'Multiple reasons'), ('Other', 'Other')], max_length=64),
        ),
    ]
