# Generated by Django 4.2.11 on 2026-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_aob_feedback_cash_payment_feedback_chance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('Waiting time before being seen', 'Waiting time before being seen'), ('Respect and dignity from staff', 'Respect and dignity from staff'), ('Cleanliness of the health facility', 'Cleanliness of the health facility'), ('Explanation of your illness and treatment', 'Explanation of your illness and treatment'), ('Availability of Medication', 'Availability of Medication'), ('Privacy', 'Privacy'), ('Service Quality', 'Service Quality'), ('Youth Friendly Services', 'Youth Friendly Services')], max_length=64),
        ),
    ]
