# Generated by Django 4.2.11 on 2026-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='age_group',
            field=models.CharField(blank=True, choices=[('15-24 years', '15-24 years'), ('25-34 years', '25-34 years'), ('35-49 years', '35-49 years'), ('50-64 years', '50-64 years'), ('65+ years', '65+ years')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')], max_length=24),
        ),
    ]
