# Generated by Django 5.2.3 on 2026-06-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_age_group_alter_feedback_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='aob_other',
            field=models.TextField(blank=True, help_text="Specify if 'Other' is selected for AOB"),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reason_not_chance_other',
            field=models.TextField(blank=True, help_text="Specify if 'Other' is selected for reason_not_chance"),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reason_not_received_other',
            field=models.TextField(blank=True, help_text="Specify if 'Other' is selected for reason_not_received"),
        ),
        migrations.AddField(
            model_name='feedback',
            name='service_other',
            field=models.TextField(blank=True, help_text="Specify if 'Other' is selected for service"),
        ),
    ]
