# Generated by Django 4.2.11 on 2026-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedback_aob_other_feedback_reason_not_chance_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='change_other',
            field=models.TextField(blank=True, help_text="Specify if 'Other' is selected for change"),
        ),
        migrations.AddField(
            model_name='feedback',
            name='insurance_other',
            field=models.TextField(blank=True, help_text="Specify if 'Other' is selected for insurance"),
        ),
    ]
