# Generated by Django 4.2.11 on 2026-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_feedback_change_other_feedback_insurance_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='insurance_other',
        ),
        migrations.AddField(
            model_name='feedback',
            name='no_insurance_reason_other',
            field=models.TextField(blank=True, help_text="Specify if 'Other' is selected for no_insurance_reason"),
        ),
    ]
