# Generated by Django 4.2.11 on 2026-06-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_remove_feedback_insurance_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='cash_payment_other',
            field=models.TextField(blank=True, help_text="Specify if 'Other' is selected for cash_payment"),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='aob',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Other', 'Other')], max_length=32),
        ),
    ]
