# Generated by Django 4.2.11 on 2026-06-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_feedback_cash_payment_other_alter_feedback_aob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='aob',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=32),
        ),
    ]
