# Generated by Django 4.2.11 on 2026-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_feedback_aob'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('Hospital', 'Hospital'), ('Bigger Clinic', 'Bigger Clinic'), ('Other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='facility_type_other',
            field=models.TextField(blank=True, help_text="Specify if 'Other' is selected for facility_type"),
        ),
    ]
