# Generated by Django 4.2.11 on 2026-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_feedback_facility_type_feedback_facility_type_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='change',
            field=models.CharField(blank=True, choices=[('More health workers available', 'More health workers available'), ('More medicines in stock', 'More medicines in stock'), ('Shorter waiting time', 'Shorter waiting time'), ('Lower costs / no fees', 'Lower costs / no fees'), ('Better staff attitude', 'Better staff attitude'), ('Longer opening hours', 'Longer opening hours'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='cost',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Applicable', 'Not Applicable'), ('Not sure', 'Not sure')], max_length=32),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Seeing (even with glasses)', 'Seeing (even with glasses)'), ('Hearing (even with hearing aid)', 'Hearing (even with hearing aid)'), ('Walking or climbing steps', 'Walking or climbing steps'), (' Remembering or concentrating', ' Remembering or concentrating'), ('Self-care (washing, dressing)', 'Self-care (washing, dressing)'), ('Communicating', 'Communicating'), (' No difficulty', ' No difficulty')], max_length=32),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='insurance',
            field=models.CharField(blank=True, choices=[('NHIMA (National Health Insurance)', 'NHIMA (National Health Insurance)'), ('Private Insurance', 'Private Insurance'), ('Both NHIMA and private', 'Both NHIMA and private'), ('None', 'None'), ('Not sure', 'Not sure')], max_length=64),
        ),
    ]
