# Generated by Django 5.2.3 on 2026-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_alter_feedback_change_alter_feedback_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='difficulty_json',
            field=models.JSONField(blank=True, default=list, help_text='Select all that apply'),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE feedback_feedback 
            SET difficulty_json = CASE 
                WHEN difficulty IS NULL OR difficulty = '' THEN '[]'::jsonb
                ELSE jsonb_build_array(difficulty::text)
            END
            """,
            reverse_sql="UPDATE feedback_feedback SET difficulty_json = '[]'::jsonb"
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='difficulty',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='difficulty_json',
            new_name='difficulty',
        ),
    ]
