# Generated by Django 4.2.11 on 2026-07-22 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_existing_feedback_metadata(apps, schema_editor):
    Feedback = apps.get_model("feedback", "Feedback")
    for entry in Feedback.objects.filter(submitted_on__isnull=True):
        if entry.created_at:
            entry.submitted_on = entry.created_at.date()
            entry.save(update_fields=["submitted_on"])


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0014_convert_difficulty_to_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('programme_name', models.CharField(blank=True, max_length=255)),
                ('collection_method', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_sessions', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_sessions', to='facilities.facility')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('complete_collectionsession', 'Can complete collection session'), ('capture_assisted_feedback', 'Can capture assisted feedback')],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_feedback_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission_source',
            field=models.CharField(choices=[('qr_public', 'Public QR Submission'), ('assisted_capture', 'Assisted Capture'), ('spreadsheet_import', 'Spreadsheet Import')], db_index=True, default='qr_public', max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('scope', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_file', models.FileField(upload_to='bulk_imports/')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validation_failed', 'Validation failed'), ('ready', 'Ready'), ('importing', 'Importing'), ('completed', 'Completed'), ('partially_completed', 'Partially completed'), ('rolled_back', 'Rolled back'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=24)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('collection_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='feedback.collectionsession')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='facilities.facility')),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_back_import_batches', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'permissions': [('validate_importbatch', 'Can validate import batch'), ('confirm_importbatch', 'Can confirm import batch'), ('rollback_importbatch', 'Can roll back import batch'), ('download_import_errors', 'Can download import errors')],
            },
        ),
        migrations.CreateModel(
            name='BulkActionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_action_logs', to=settings.AUTH_USER_MODEL)),
                ('collection_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='feedback.collectionsession')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='feedback.importbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='collection_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='feedback.collectionsession'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='feedback.importbatch'),
        ),
        migrations.RunPython(backfill_existing_feedback_metadata, migrations.RunPython.noop),
    ]
