# Generated by Django 4.2.11 on 2026-08-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_update_age_group_15_24_to_18_24'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ratingresponse',
            new_name='feedback_ra_submiss_bb2f9c_idx',
            old_name='feedback_rat_submiss_c9f0b1_idx',
        ),
        migrations.RenameIndex(
            model_name='ratingresponse',
            new_name='feedback_ra_categor_f68308_idx',
            old_name='feedback_rat_categor_5017fe_idx',
        ),
    ]
