# Generated by Django 4.2.11 on 2026-08-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_update_age_group_15_24_to_18_24'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relname = 'feedback_rat_submiss_c9f0b1_idx'
                        ) THEN
                            ALTER INDEX feedback_rat_submiss_c9f0b1_idx
                            RENAME TO feedback_ra_submiss_bb2f9c_idx;
                        ELSIF NOT EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relname = 'feedback_ra_submiss_bb2f9c_idx'
                        ) THEN
                            CREATE INDEX feedback_ra_submiss_bb2f9c_idx
                            ON feedback_ratingresponse (submission_id, category);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relname = 'feedback_ra_submiss_bb2f9c_idx'
                        ) THEN
                            ALTER INDEX feedback_ra_submiss_bb2f9c_idx
                            RENAME TO feedback_rat_submiss_c9f0b1_idx;
                        ELSIF NOT EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relname = 'feedback_rat_submiss_c9f0b1_idx'
                        ) THEN
                            CREATE INDEX feedback_rat_submiss_c9f0b1_idx
                            ON feedback_ratingresponse (submission_id, category);
                        END IF;
                    END
                    $$;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relname = 'feedback_rat_categor_5017fe_idx'
                        ) THEN
                            ALTER INDEX feedback_rat_categor_5017fe_idx
                            RENAME TO feedback_ra_categor_f68308_idx;
                        ELSIF NOT EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relname = 'feedback_ra_categor_f68308_idx'
                        ) THEN
                            CREATE INDEX feedback_ra_categor_f68308_idx
                            ON feedback_ratingresponse (category);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relname = 'feedback_ra_categor_f68308_idx'
                        ) THEN
                            ALTER INDEX feedback_ra_categor_f68308_idx
                            RENAME TO feedback_rat_categor_5017fe_idx;
                        ELSIF NOT EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relname = 'feedback_rat_categor_5017fe_idx'
                        ) THEN
                            CREATE INDEX feedback_rat_categor_5017fe_idx
                            ON feedback_ratingresponse (category);
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='ratingresponse',
                    name='feedback_rat_submiss_c9f0b1_idx',
                ),
                migrations.AddIndex(
                    model_name='ratingresponse',
                    index=models.Index(
                        fields=['submission', 'category'],
                        name='feedback_ra_submiss_bb2f9c_idx',
                    ),
                ),
                migrations.RemoveIndex(
                    model_name='ratingresponse',
                    name='feedback_rat_categor_5017fe_idx',
                ),
                migrations.AddIndex(
                    model_name='ratingresponse',
                    index=models.Index(
                        fields=['category'],
                        name='feedback_ra_categor_f68308_idx',
                    ),
                ),
            ],
        ),
    ]
